/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author manana
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMAltaNeu = new javax.swing.JMenuItem();
        jMListadoNeu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMAñadirFactura = new javax.swing.JMenuItem();
        jMGenerarPDF = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/images.jpg"))); // NOI18N

        jMenu1.setText("Neumáticos");

        jMAltaNeu.setText("Alta Neumaticos");
        jMAltaNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAltaNeuActionPerformed(evt);
            }
        });
        jMenu1.add(jMAltaNeu);

        jMListadoNeu.setText("Listado Neumáticos");
        jMListadoNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMListadoNeuActionPerformed(evt);
            }
        });
        jMenu1.add(jMListadoNeu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Facturación");

        jMAñadirFactura.setText("Añadir Factura");
        jMAñadirFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMAñadirFacturaActionPerformed(evt);
            }
        });
        jMenu2.add(jMAñadirFactura);

        jMGenerarPDF.setText("Generar PDF");
        jMGenerarPDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMGenerarPDFActionPerformed(evt);
            }
        });
        jMenu2.add(jMGenerarPDF);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMAltaNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAltaNeuActionPerformed
        new AltaNeumatico(this, true).setVisible(true);
    }//GEN-LAST:event_jMAltaNeuActionPerformed

    private void jMListadoNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMListadoNeuActionPerformed
        new listadoNeumaticos(this, true).setVisible(true);
    }//GEN-LAST:event_jMListadoNeuActionPerformed

    private void jMAñadirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMAñadirFacturaActionPerformed
        new CrearFactura(this, true).setVisible(true);
    }//GEN-LAST:event_jMAñadirFacturaActionPerformed

    private void jMGenerarPDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMGenerarPDFActionPerformed
       new GenerarPDF(this, true).setVisible(true);
    }//GEN-LAST:event_jMGenerarPDFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMAltaNeu;
    private javax.swing.JMenuItem jMAñadirFactura;
    private javax.swing.JMenuItem jMGenerarPDF;
    private javax.swing.JMenuItem jMListadoNeu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
